# Generated by Django 3.2.4 on 2021-06-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
