# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/ZSRecruitment

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python -m venv venv
            . venv/Scripts/activate
            pip install -r requirements.txt
      - run:
          name: migrate models
          command: |
            venv/Scripts/activate
            py manage.py migrate
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/Scripts/activate
            pytest
            
